# Wanna be lazy? Just plug a DSN string here
POSTGRES_DSN = "postgres://postgres:postgres@localhost:5432/postgres"

# ...or supply all of these for more modular control
POSTGRES_USER = "..."
POSTGRES_PASSWORD = "..."
POSTGRES_DATABASE = "..."

POSTGRES_HOST = "..."  # This is optional


# You'll need this to run the bot
TOKEN = "..."
