name: i-hate-discord-bots

services:
    database:
        image: postgres:16.2-alpine
        healthcheck:
            test: "pg_isready -d $POSTGRES_DATABASE -U $POSTGRES_USER"
            interval: 1s
            retries: 100
        restart: always
        shm_size: 128mb
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
        volumes:
            - database:/var/lib/postgresql

    database-admin-panel:
        depends_on:
            database:
                condition: service_healthy
        image: elestio/pgadmin:REL-8_0
        profiles:
            - pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: example@example.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin
            PGADMIN_LISTEN_PORT: 8080
        ports:
            - "8080:8080"
        volumes:
            - database:/pgadmin4/servers.json

    bot:
        depends_on:
            database:
                condition: service_healthy
        build:
            context: .
        restart: always

volumes:
    database:
