[tool.black]
line-length = 120
force-exclude = "__init__.py"

[tool.isort]
combine_as_imports = true
combine_star = true
line_length = 120
profile = "black"

[tool.pyright]
pythonversion = "^3.12"
typeCheckingMode = "strict"
reportIncompatibleMethodOverride = false
