# TODO: Figure out a way to define the database once in a separate compose file
# then extend this compose file with it for unified changes to the database
name: devcontainer

services:
    workspace:
        image: mcr.microsoft.com/devcontainers/python:1-3.12
        restart: always
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
        network_mode: service:database

    database:
        image: postgres:16.2-alpine
        restart: always
        shm_size: 128mb
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
        volumes:
            - database:/var/lib/postgresql

volumes:
    database:
