__all__ = (
    "HOME_GUILD_ID",
    "PREFIXES",
    "EMOJIS",
)

HOME_GUILD_ID = 774561547930304536
IMAGINARY_BALLS_SYNONYMS = ["rolleo"]
BALLS_SYNONYMS = [
    "ball",
    "testicle",
    "nut",
    "family jewel",
    "ballock",
    "gonad",
    "male genital",
    "rock",
    "stone",
    "teste",
    "genital",
    *IMAGINARY_BALLS_SYNONYMS,
]
I18N_BALLS_SYNONYMS = ["testicolo", "testicoli"]


class Emojis:
    CHECKMARK = "\N{WHITE HEAVY CHECK MARK}"
    CROSS = "\N{CROSS MARK}"
    LEFT_ARROW = "\N{LEFTWARDS BLACK ARROW}\N{VARIATION SELECTOR-16}"
    LEFT_SPEECH_BUBBLE = "\N{LEFT SPEECH BUBBLE}\N{VARIATION SELECTOR-16}"
    PIN = "\N{PUSHPIN}"
    RIGHT_ARROW = "\N{BLACK RIGHTWARDS ARROW}\N{VARIATION SELECTOR-16}"
    ROBOT_FACE = "\N{ROBOT FACE}"
    TRASH = "\N{WASTEBASKET}"

    ONE = "\N{DIGIT ONE}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
    TWO = "\N{DIGIT TWO}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
    THREE = "\N{DIGIT THREE}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
    FOUR = "\N{DIGIT FOUR}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
    FIVE = "\N{DIGIT FIVE}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
    SIX = "\N{DIGIT SIX}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
    SEVEN = "\N{DIGIT SEVEN}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
    EIGHT = "\N{DIGIT EIGHT}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
    NINE = "\N{DIGIT NINE}\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"

    @property
    def DIGITS(self):
        return (self.ONE, self.TWO, self.THREE, self.FOUR, self.FIVE, self.SIX, self.SEVEN, self.EIGHT, self.NINE)


def pluralise(text: str):
    case_agnostic = text.lower()

    return text if case_agnostic.endswith("s") else f"{text}s"


EMOJIS = Emojis()
PREFIXES = tuple(f"{prefix} " for prefix in [*BALLS_SYNONYMS, *I18N_BALLS_SYNONYMS, *map(pluralise, BALLS_SYNONYMS)])
